task: teacher

defaults:
    - _self_
    - agent: mcts-lm
    - theory: groups

iterations: 5
n_conjectures: 200

difficulty_buckets:
    - hard: 20
    - easy: 50
    - triv: 100

train_policy_on_hindsight_examples: true
freeze_conjecturer: false
continue: /network/scratch/m/moksh.jain/minimo_experiments/repro
job:
    wandb_project: minimo
    name: test_full

hydra:
    job:
        chdir: true
    run:
        dir: /network/scratch/m/moksh.jain/minimo_experiments/${job.name}/